# CP Feb 2018. Receives NZ projections for a species as generated by CLIMEX MCR (csv file 'nz_proj') & the species name ('sp_to_map') & returns a picture of NZ CMIs.
# 27-Mar-2018: In this version, I've added an outline of NZ. For details, see M:\Documents\R_examples\GIS\exDownloadCountryOutlineClipAndSave.r

fGgplotNzClimexMcrProjection <- function(nz_proj, sp_to_map) {

	library(ggplot2)

  source('fGetColorsToPlotAClimexMcrProjection.r')

	load('nz_outline_and_admins_shp.RData') # nz_borders

  nz_df <- fortify(nz_borders)

	cols <- fGetColorsToPlotAClimexMcrProjection(nz_proj$cmiRnd)

	map <- 
		ggplot() +
			theme_bw() +
			geom_point(data = nz_proj, aes(x = Loc1Lon, y = Loc1Lat, color = as.factor(cmiRnd)), pch = 15, size = 1) +
			scale_color_manual(values = cols) +
			guides(color = guide_legend(override.aes = list(size = 6))) + # dot size
			theme(axis.ticks = element_blank(), 
			axis.text.x = element_blank(), 
			axis.title.x = element_blank(), 
			axis.text.y = element_blank(),  
			axis.title.y = element_blank(),
			plot.title = element_text(size = 18, hjust = 0.5, face = 'italic'),
			legend.position = c(.3, .7),
			legend.background = element_rect(color = 'grey50')) +
			coord_equal() +
			ggtitle(sp_to_map) +
			labs(color = 'CMI') +
			geom_map(data = nz_df, map = nz_df, aes(map_id = id, x = long, y = lat), color = 'grey70', fill = 'transparent')

	return(map)
}
